library(ggplot2)
library(readr)
library(UpSetR)

setwd("~/Desktop/Results/Raw_results_data_all_teams/connectedComponents")

upsetDataComplete <- read_delim("upsetDataComplete.csv", ";",escape_double = FALSE, trim_ws = TRUE)
upsetDataInclusions <- read_delim("upsetDataInclusions.csv", ";", escape_double = FALSE, trim_ws = TRUE)

upset(as.data.frame(upsetDataComplete),order.by = "freq")
upset(as.data.frame(upsetDataInclusions),order.by = "freq")


# this script serves to calculate and save the basic statistical information about the connected components
# generated by our analysis.

# datasets of complete and inclusion graphs.
completeData  = read.csv("statsComplete.csv", sep=";")
inclusionData = read.csv("inclusionsStats.csv", sep=";")
length(inclusionData$component)


beforeClique <- function(dataset){
  results = dataset[grep("*_after", dataset$component, invert=TRUE), ]
  
  
  return(results)
}

afterClique <- function(dataset){
  results = dataset[grep("*_before", dataset$component, invert=TRUE),]
  
  
  return(results)
}


numCC <- function(dataset){
  results = length(dataset$component)
  
  return(results)
}


avgNodesPerCC <- function(dataset){
  results = mean(dataset$num.Nodes)
  
  return(results)
}

avgLengthPerCC <- function(dataset){
  results = mean(dataset$avg.length)
  return (results)
}


cliquePercent <- function(dataset){
  cliques = dataset[dataset$Clique == "True",]
  percentage = (length(cliques$component) / length(dataset$component)) * 100
  
  
  return(percentage)
}


# number of connected components present in the dataset
numCC(completeData)
numCC(inclusionData)


before = beforeClique(completeData)
after = afterClique(completeData)
# average number of nodes per connected components.
# before
avgNodesPerCC(before)

# after
avgNodesPerCC(after)


# Average length for all connected components
avgLengthPerCC(before)
avgLengthPerCC(after)


cliquePercent(before)
cliquePercent(after)

cliquePercent(beforeClique(inclusionData))
cliquePercent(afterClique(inclusionData))

# total number of clusters

length(before$component)

# Histograms of # sequences per CC
hist(before$num.Nodes[before$num.Nodes > 2],breaks=700,ylim=c(0,50),xlim=c(0,100))


### Generating the numbers for the Statistical table comparing the two 

##For 0.80%

# number of CC

length(before$num.Nodes[before$num.Nodes == 2]) # num. of nodes == 2
length(before$num.Nodes[before$num.Nodes == 3])

length(before$num.Nodes[before$num.Nodes == 4])
length(before$num.Nodes[before$num.Nodes == 5])
length(before$num.Nodes[before$num.Nodes > 5 ]) # num of nodes > 5
length(before$num.Nodes) # total

# Percentage of total CC

length(before$num.Nodes[before$num.Nodes == 2]) / length(before$num.Nodes) * 100
length(before$num.Nodes[before$num.Nodes == 3]) / length(before$num.Nodes) * 100
length(before$num.Nodes[before$num.Nodes == 4]) / length(before$num.Nodes) * 100
length(before$num.Nodes[before$num.Nodes == 5]) / length(before$num.Nodes) * 100
length(before$num.Nodes[before$num.Nodes >5]) / length(before$num.Nodes) * 100



# % of cliques in
cliquePercent(before[before$num.Nodes == 2,])
cliquePercent(before[before$num.Nodes == 3,])
cliquePercent(before[before$num.Nodes == 4,])
cliquePercent(before[before$num.Nodes == 5,])
cliquePercent(before[before$num.Nodes > 5,])


## for 0.95%










################


# Histogram of # of total edges:
hist(before$num.Edges)
hist(after$num.Edges)

#log scale to determine where to cut

boxplot(before$avg.Score[before$avg.Score],after$avg.Score[after$avg.Score],
        notch=TRUE,
        log="y",
        names = c("before","after"),
        xlab = "before/after addition of lower quality connections",
        ylab = "Bitscores (Log scale) "
        )

# adjusted to remove outliers
boxplot(before$avg.Score[before$avg.Score<1200],after$avg.Score[after$avg.Score<1200],
        notch=TRUE,
        #log="y",
        names = c("before","after"),
        xlab = "before/after addition of lower quality connections",
        ylab = "Bitscores (Log scale) ",
        outline=FALSE
)
